spring.application.name=RateShield

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/rateshield
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

spring.data.redis.host=localhost
spring.data.redis.port=6379